[target.x86_64-unknown-linux-gnu]
image = "quickwitinc/x86_64-unknown-linux-gnu:latest"

[target.x86_64-unknown-linux-musl]
image = "quickwitinc/x86_64-unknown-linux-musl:latest"

[target.aarch64-unknown-linux-gnu]
image = "quickwitinc/aarch64-unknown-linux-gnu:latest"

[target.aarch64-unknown-linux-musl]
image = "quickwitinc/aarch64-unknown-linux-musl:latest"













# [target.armv7-unknown-linux-gnueabihf]
# image = "quickwitinc/armv7-unknown-linux-gnueabihf:latest"

# [target.armv7-unknown-linux-musleabihf]
# image = "quickwitinc/armv7-unknown-linux-musleabihf:latest"
